Added new job to the CI test, test 2 frameworks on 1 use case

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -55,7 +55,7 @@ jobs:
         run: make test-unit
 
 
-  run-generation-tests:
+  run-generation-tests-default-framework:
     if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
     timeout-minutes: 30
     runs-on: ubuntu-latest
@@ -106,6 +106,57 @@ jobs:
 
       - name: Run Generation Test - ${{ matrix.prompt_id }}
         run: make test-single-turn-generation-e2e PROMPT_ID=${{ matrix.prompt_id }}
+
+  run-generation-tests-alternate-frameworks:
+    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
+    timeout-minutes: 30
+    runs-on: ubuntu-latest
+    needs: run-unit-tests
+    strategy:
+      fail-fast: false
+      matrix:
+        agent_framework:
+          - openai
+          - langchain
+
+    steps:
+      - name: Check out the repository
+        uses: actions/checkout@v4
+
+      - name: Install the latest version of uv and set the python version to 3.13
+        uses: astral-sh/setup-uv@v6
+        with:
+          python-version: 3.13
+          activate-environment: true
+
+      - name: Cache mcpd binary
+        id: cache-mcpd
+        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
+        with:
+          key: mcpd-${{ vars.MCPD_VERSION }}-Linux-x86_64
+          path: /usr/local/bin/mcpd
+
+      - name: Install mcpd (if not cached)
+        if: steps.cache-mcpd.outputs.cache-hit != 'true'
+        run: |
+          version="${{ vars.MCPD_VERSION }}"
+          if [ -z "$version" ]; then
+            echo "MCPD_VERSION var is not set, or empty"
+            exit 1
+          fi
+          zip="mcpd_Linux_x86_64.tar.gz"
+          url="https://github.com/mozilla-ai/mcpd/releases/download/${version}/${zip}"
+          curl -fsSL "$url" -o "$zip" || { echo "download failed"; exit 1; }
+          tar -xzf "$zip" mcpd || { echo "extract failed"; exit 1; }
+          sudo mv mcpd /usr/local/bin/mcpd && sudo chmod +x /usr/local/bin/mcpd || { echo "Install failed"; return 1; }
+          rm -f "$zip"
+
+      - name: Create .env file from GitHub secrets
+        run: |
+          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
+
+      - name: Run Generation Test - ${{ matrix.agent_framework }}
+        run: FRAMEWORK=${{ matrix.agent_framework }} make test-single-turn-generation-e2e PROMPT_ID=scoring-blueprints-submission
 
   run-agent-evaluation-tests:
     if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
